### ISSUE TITLE
Export to Frontmatter + Markdown?

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/papercall-api-import#1]
Once feature which would save a ton of time would be the option to export to markdown (with frontmatter) so that we can use this for the finalized talks. 

The format from last year should look like: https://github.com/jefftriplett/glowing-adventure/blob/master/_posts/talks/2016-07-17-09-00-presentation-55.md

Some of the frontmatter items like room, track, etc we won't know until we have a schedule but this will make getting everything ready for the conference much easier.

**Comment by jefftriplett** [comment]
The https://pypi.python.org/pypi/python-frontmatter/0.2.1 library is really nice and will save you time too.

**Comment by FlipperPA** [comment]
This should be easy enough to do.

**Comment by jefftriplett** [comment]
We fixed this!!!
